apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  namespace: testsg
  name: allow-access
spec:
  podSelector:
    matchLabels:
      app: nginx-demo
  securityGroups:
    groupIds:
      - sg-0cb15500af784e3e1

