apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: whb-karpenter-demo
  region: us-east-1 
 
nodeGroups:
  - name: new-unmanaged1111-nodegroup
    amiFamily: AmazonLinux2
    instanceType: c5.xlarge
    desiredCapacity: 1 
    minSize: 1
    maxSize: 2
    volumeSize: 80 
    volumeType: gp3
    securityGroups:
      attachIDs:
        - sg-040d93b4cf647e3d1
    subnets:
      - subnet-00200ddcd5981b478
      - subnet-0d052e94ee892f5e4
