apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations: 
  - effect: NoSchedule 
    key: node-role.kubernetes.io/master
  - key: CriticalAddonsOnly 
    operator: Exists
