apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 1296000
  providerRef:
    name: default
  kubeletConfiguration:
    systemReserved:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 1Gi
    kubeReserved:
      cpu: 500m
      memory: 500Mi
      ephemeral-storage: 3Gi
    evictionHard:
      memory.available: 5%
      nodefs.available: 10%
      nodefs.inodesFree: 10%
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    aws-ids: "subnet-00200ddcd5981b478,subnet-0d052e94ee892f5e4,subnet-0b27b8e984c6269f6,subnet-03dd270e56faaed0c"
  securityGroupSelector:
    aws-ids: "sg-040d93b4cf647e3d1,sg-0e85ca77a16d7999a"
  amiFamily: Bottlerocket

